### ISSUE TITLE
Print warning message when use 1.8.11 swag to generate swagger document

### ISSUE THREAD

**Issue by ningyougang** [swaggo/swag#1516]
**Describe the bug**

When use latest swag(v1.8.11) to generate swagger doc, has below warning message,
But a good news is, finally, the swagger document is generated successfully.

**To Reproduce**
* Download latest swag: https://github.com/swaggo/swag/releases/tag/v1.8.11 to `/root/swag`
* execute `/root/swag init --parseDependency --parseInternal --parseDepth 1 -g ./main.go`, report below warning message

```
# /root/swag init --parseDependency --parseInternal --parseDepth 1 -g ./main.go
2023/03/28 11:24:34 Generate swagger docs....
2023/03/28 11:24:34 Generate general API Info, search dir:./
2023/03/28 11:24:45 warning: failed to evaluate const t1 at /home/go/src/unicode/utf8/utf8.go:29:2, strconv.ParseUint: parsing "b00000000": invalid syntax
2023/03/28 11:24:45 warning: failed to evaluate const tx at /home/go/src/unicode/utf8/utf8.go:30:2, strconv.ParseUint: parsing "b10000000": invalid syntax
2023/03/28 11:24:45 warning: failed to evaluate const t2 at /home/go/src/unicode/utf8/utf8.go:31:2, strconv.ParseUint: parsing "b11000000": invalid syntax
2023/03/28 11:24:45 warning: failed to evaluate const t3 at /home/go/src/unicode/utf8/utf8.go:32:2, strconv.ParseUint: parsing "b11100000": invalid syntax
2023/03/28 11:24:45 warning: failed to evaluate const t4 at /home/go/src/unicode/utf8/utf8.go:33:2, strconv.ParseUint: parsing "b11110000": invalid syntax
2023/03/28 11:24:45 warning: failed to evaluate const t5 at /home/go/src/unicode/utf8/utf8.go:34:2, strconv.ParseUint: parsing "b11111000": invalid syntax
2023/03/28 11:24:45 warning: failed to evaluate const maskx at /home/go/src/unicode/utf8/utf8.go:36:2, strconv.ParseUint: parsing "b00111111": invalid syntax
2023/03/28 11:24:45 warning: failed to evaluate const mask2 at /home/go/src/unicode/utf8/utf8.go:37:2, strconv.ParseUint: parsing "b00011111": invalid syntax
2023/03/28 11:24:45 warning: failed to evaluate const mask3 at /home/go/src/unicode/utf8/utf8.go:38:2, strconv.ParseUint: parsing "b00001111": invalid syntax
2023/03/28 11:24:45 warning: failed to evaluate const mask4 at /home/go/src/unicode/utf8/utf8.go:39:2, strconv.ParseUint: parsing "b00000111": invalid syntax
2023/03/28 11:24:45 warning: failed to evaluate const locb at /home/go/src/unicode/utf8/utf8.go:46:2, strconv.ParseUint: parsing "b10000000": invalid syntax
2023/03/28 11:24:45 warning: failed to evaluate const hicb at /home/go/src/unicode/utf8/utf8.go:47:2, strconv.ParseUint: parsing "b10111111": invalid syntax
2023/03/28 11:24:45 warning: failed to evaluate const mProfCycleWrap at /home/go/src/runtime/mprof.go:159:7, reflect: call of reflect.Value.Len on zero Value
...
2023/03/28 11:24:45 create docs.go at docs/docs.go
2023/03/28 11:24:45 create swagger.json at docs/swagger.json
2023/03/28 11:24:45 create swagger.yaml at docs/swagger.yaml
```

**Expected behavior**

* No any warning message (Has warning message)
* Swagger doc is created successfully (This is ok)

**Screenshots**

**Your swag version**
e.g. 1.8.11

**Your go version**
e.g. 1.17.13

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 22

**Comment by huqiuyun** [comment]
on mac computer , and not generate right doc

**Comment by panhow** [comment]
`Linux tester 5.15.0-69-generic #76~20.04.1-Ubuntu`
got same problem on v1.8.12

**Comment by jianjianxu** [comment]
I got this too:
```
2023/06/07 11:12:36 warning: failed to get package name in dir: ./, error: execute go list command, exit status 1, stdout:, stderr:no Go files in /home/jianjianxu/work/projects/fzpm2022_api_go
2023/06/07 11:12:38 warning: failed to evaluate const locb at /home/ko/go/pkg/mod/github.com/pelletier/go-toml/v2@v2.0.6/internal/characters/utf8.go:183:2, strconv.ParseUint: parsing "b10000000": invalid syntax
2023/06/07 11:12:38 warning: failed to evaluate const hicb at /home/ko/go/pkg/mod/github.com/pelletier/go-toml/v2@v2.0.6/internal/characters/utf8.go:184:2, strconv.ParseUint: parsing "b10111111": invalid syntax
```

**Comment by ningyougang** [comment]
After upgrade the swag version to
``
[root@localhost elb-apiserver]# swag --version
swag version v1.8.12
```
The problem gone

**Comment by sundowndev** [comment]
This got fixed in v1.16.3 with go1.20

**Comment by sundowndev** [comment]
@prologic The upgrade fixed it for me on go1.20, you're using go1.22 so I don't know. May be it was specific to my project.

**Comment by only1970** [comment]
> This got fixed in v1.16.3 with go1.20

@sundowndev I'm running the specified version:

```
$ go version 
go version go1.20.2
$ swag --version
swag version v1.16.3
```

 And the problem still exists：
```
$ swag init --parseDependency --parseInternal
2024/05/11 18:58:01 Generate swagger docs....
2024/05/11 18:58:01 Generate general API Info, search dir:./
2024/05/11 18:58:02 warning: failed to evaluate const mProfCycleWrap at /usr/local/go/src/runtime/mprof.go:165:7, reflect: call of reflect.Value.Len on zero Value
...
```

**Comment by supuwoerc** [comment]
+1
