### ISSUE TITLE
Wrong parse of [][]string

### ISSUE THREAD

**Issue by art-frela** [swaggo/swag#562]
**Describe the bug**
When a struct has field(s) of [][]string type, `swag init` makes Unknown Type

**To Reproduce**
1. make struct
```golang
// Content is universal content type, table and raw
type Content struct {
	Headers []string    `bson:"headers" json:"headers" swaggertype:"array,string"`
	Table   [][]string  `bson:"table" json:"table"`
	Raw     interface{} `bson:"raw" json:"raw"`
}
```
2. add this struct to the // @Success description
```golang
// @Success 200 {object} Content
// @Router /api/v2/docs/ [get]
```
3. save and run `swag init`
4. look your output file /path/to/docs.go

```json
"table": {
                    "type": "array",
                    "items": {
                        "type": "\u0026{%!s(token.Pos=1477) \u003cnil\u003e string}"
                    }
                }
```

**Expected behavior**
It's [swagger array](https://swagger.io/docs/specification/data-models/data-types/#array)
that is why docs.go must be
```json
"table": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items":{
                            "type": "string"
                        }
                    }
                }
```

**Screenshots**
with error 
![Swagger_wrong](https://user-images.githubusercontent.com/32013768/68943446-4456b280-07bc-11ea-90e6-a3023c4bad24.png)

after hand fix docs.go

![Swagger_correct](https://user-images.githubusercontent.com/32013768/68943460-5173a180-07bc-11ea-876b-72b434c11f10.png)

**Your swag version**
`swag version v1.4.0`

**Your go version**
`go version go1.13.1 darwin/amd64`

**Desktop (please complete the following information):**
 - OS: macOS Catalina v10.15.1
 - Browser: [chrome]
 - Version: [78.0.3904.97]

**Additional context**
In the dockerized app have same behavior

**Comment by NamelessHH** [comment]
My issue is very similar https://github.com/swaggo/swag/issues/584

**Comment by easonlin404** [comment]
fixed by #588 , please help test against the latest master branch.

**Comment by art-frela** [comment]
> fixed by #588 , please help test against the latest master branch.

Thank You!

Manualy tested - all ok.

```json
"content": {
    "headers": [
      "string"
    ],
    "raw": {},
    "table": [
      [
        "string"
      ]
    ]
  },```

**Comment by tejaskale** [comment]
This unfortunately still fails on float 2-D arrays. For eg:  
```go
// Content is universal content type, table and raw
type Content struct {
	Headers []string    `bson:"headers" json:"headers" swaggertype:"array,string"`
	Table   [][]float64  `bson:"table" json:"table"`
	Raw     interface{} `bson:"raw" json:"raw"`
}
```
Generates : 

```json
...
 "table": {
                    "type": "array",
                    "items": {
                        "type": "\u0026{%!s(token.Pos=151) \u003cnil\u003e float64}"
                    }
                }
...
```
